rclone mount ac:/31/ /mnt/31/ --drive-service-account-file /root/31.json --vfs-read-chunk-size 64k --vfs-cache-max-size 1G --transfers 128 --checkers 256 --drive-pacer-min-sleep 1ms --drive-pacer-burst 200 --poll-interval 224h --vfs-cache-mode full --dir-cache-time 1000000h --vfs-cache-max-age 1000000h --vfs-cache-poll-interval 33332m --max-read-ahead 128k --vfs-read-ahead 32k --vfs-read-wait 0 --buffer-size off --vfs-read-chunk-size-limit 32k --no-check-dest --no-checksum --no-modtime --no-traverse --read-only --daemon
sleep 2
rclone mount ac:/32/ /mnt/32/ --drive-service-account-file /root/32.json --vfs-read-chunk-size 64k --vfs-cache-max-size 1G --transfers 128 --checkers 256 --drive-pacer-min-sleep 1ms --drive-pacer-burst 200 --poll-interval 224h --vfs-cache-mode full --dir-cache-time 1000000h --vfs-cache-max-age 1000000h --vfs-cache-poll-interval 33332m --max-read-ahead 128k --vfs-read-ahead 32k --vfs-read-wait 0 --buffer-size off --vfs-read-chunk-size-limit 32k --no-check-dest --no-checksum --no-modtime --no-traverse --read-only --daemon
sleep 2
rclone mount ac:/33/ /mnt/33/ --drive-service-account-file /root/33.json --vfs-read-chunk-size 64k --vfs-cache-max-size 1G --transfers 128 --checkers 256 --drive-pacer-min-sleep 1ms --drive-pacer-burst 200 --poll-interval 224h --vfs-cache-mode full --dir-cache-time 1000000h --vfs-cache-max-age 1000000h --vfs-cache-poll-interval 33332m --max-read-ahead 128k --vfs-read-ahead 32k --vfs-read-wait 0 --buffer-size off --vfs-read-chunk-size-limit 32k --no-check-dest --no-checksum --no-modtime --no-traverse --read-only --daemon
sleep 2
rclone mount ac:/34/ /mnt/34/ --drive-service-account-file /root/34.json --vfs-read-chunk-size 64k --vfs-cache-max-size 1G --transfers 128 --checkers 256 --drive-pacer-min-sleep 1ms --drive-pacer-burst 200 --poll-interval 224h --vfs-cache-mode full --dir-cache-time 1000000h --vfs-cache-max-age 1000000h --vfs-cache-poll-interval 33332m --max-read-ahead 128k --vfs-read-ahead 32k --vfs-read-wait 0 --buffer-size off --vfs-read-chunk-size-limit 32k --no-check-dest --no-checksum --no-modtime --no-traverse --read-only --daemon
sleep 2
rclone mount ac:/35/ /mnt/35/ --drive-service-account-file /root/35.json --vfs-read-chunk-size 64k --vfs-cache-max-size 1G --transfers 128 --checkers 256 --drive-pacer-min-sleep 1ms --drive-pacer-burst 200 --poll-interval 224h --vfs-cache-mode full --dir-cache-time 1000000h --vfs-cache-max-age 1000000h --vfs-cache-poll-interval 33332m --max-read-ahead 128k --vfs-read-ahead 32k --vfs-read-wait 0 --buffer-size off --vfs-read-chunk-size-limit 32k --no-check-dest --no-checksum --no-modtime --no-traverse --read-only --daemon
sleep 2
cd /mnt
du -h