rclone mount ac:/71/ /mnt/71/ --drive-service-account-file /root/71.json --vfs-read-chunk-size 64k --vfs-cache-max-size 1G --transfers 128 --checkers 256 --drive-pacer-min-sleep 1ms --drive-pacer-burst 200 --poll-interval 224h --vfs-cache-mode full --dir-cache-time 1000000h --vfs-cache-max-age 1000000h --vfs-cache-poll-interval 33332m --max-read-ahead 128k --vfs-read-ahead 32k --vfs-read-wait 0 --buffer-size off --vfs-read-chunk-size-limit 32k --no-check-dest --no-checksum --no-modtime --no-traverse --read-only --daemon
sleep 2
rclone mount ac:/72/ /mnt/72/ --drive-service-account-file /root/72.json --vfs-read-chunk-size 64k --vfs-cache-max-size 1G --transfers 128 --checkers 256 --drive-pacer-min-sleep 1ms --drive-pacer-burst 200 --poll-interval 224h --vfs-cache-mode full --dir-cache-time 1000000h --vfs-cache-max-age 1000000h --vfs-cache-poll-interval 33332m --max-read-ahead 128k --vfs-read-ahead 32k --vfs-read-wait 0 --buffer-size off --vfs-read-chunk-size-limit 32k --no-check-dest --no-checksum --no-modtime --no-traverse --read-only --daemon
sleep 2
rclone mount ac:/73/ /mnt/73/ --drive-service-account-file /root/73.json --vfs-read-chunk-size 64k --vfs-cache-max-size 1G --transfers 128 --checkers 256 --drive-pacer-min-sleep 1ms --drive-pacer-burst 200 --poll-interval 224h --vfs-cache-mode full --dir-cache-time 1000000h --vfs-cache-max-age 1000000h --vfs-cache-poll-interval 33332m --max-read-ahead 128k --vfs-read-ahead 32k --vfs-read-wait 0 --buffer-size off --vfs-read-chunk-size-limit 32k --no-check-dest --no-checksum --no-modtime --no-traverse --read-only --daemon
sleep 2
rclone mount ac:/74/ /mnt/74/ --drive-service-account-file /root/74.json --vfs-read-chunk-size 64k --vfs-cache-max-size 1G --transfers 128 --checkers 256 --drive-pacer-min-sleep 1ms --drive-pacer-burst 200 --poll-interval 224h --vfs-cache-mode full --dir-cache-time 1000000h --vfs-cache-max-age 1000000h --vfs-cache-poll-interval 33332m --max-read-ahead 128k --vfs-read-ahead 32k --vfs-read-wait 0 --buffer-size off --vfs-read-chunk-size-limit 32k --no-check-dest --no-checksum --no-modtime --no-traverse --read-only --daemon
sleep 2
rclone mount ac:/75/ /mnt/75/ --drive-service-account-file /root/75.json --vfs-read-chunk-size 64k --vfs-cache-max-size 1G --transfers 128 --checkers 256 --drive-pacer-min-sleep 1ms --drive-pacer-burst 200 --poll-interval 224h --vfs-cache-mode full --dir-cache-time 1000000h --vfs-cache-max-age 1000000h --vfs-cache-poll-interval 33332m --max-read-ahead 128k --vfs-read-ahead 32k --vfs-read-wait 0 --buffer-size off --vfs-read-chunk-size-limit 32k --no-check-dest --no-checksum --no-modtime --no-traverse --read-only --daemon
sleep 2
rclone mount ac:/76/ /mnt/76/ --drive-service-account-file /root/76.json --vfs-read-chunk-size 64k --vfs-cache-max-size 1G --transfers 128 --checkers 256 --drive-pacer-min-sleep 1ms --drive-pacer-burst 200 --poll-interval 224h --vfs-cache-mode full --dir-cache-time 1000000h --vfs-cache-max-age 1000000h --vfs-cache-poll-interval 33332m --max-read-ahead 128k --vfs-read-ahead 32k --vfs-read-wait 0 --buffer-size off --vfs-read-chunk-size-limit 32k --no-check-dest --no-checksum --no-modtime --no-traverse --read-only --daemon
sleep 2
rclone mount ac:/77/ /mnt/77/ --drive-service-account-file /root/77.json --vfs-read-chunk-size 64k --vfs-cache-max-size 1G --transfers 128 --checkers 256 --drive-pacer-min-sleep 1ms --drive-pacer-burst 200 --poll-interval 224h --vfs-cache-mode full --dir-cache-time 1000000h --vfs-cache-max-age 1000000h --vfs-cache-poll-interval 33332m --max-read-ahead 128k --vfs-read-ahead 32k --vfs-read-wait 0 --buffer-size off --vfs-read-chunk-size-limit 32k --no-check-dest --no-checksum --no-modtime --no-traverse --read-only --daemon
sleep 2
rclone mount ac:/78/ /mnt/78/ --drive-service-account-file /root/78.json --vfs-read-chunk-size 64k --vfs-cache-max-size 1G --transfers 128 --checkers 256 --drive-pacer-min-sleep 1ms --drive-pacer-burst 200 --poll-interval 224h --vfs-cache-mode full --dir-cache-time 1000000h --vfs-cache-max-age 1000000h --vfs-cache-poll-interval 33332m --max-read-ahead 128k --vfs-read-ahead 32k --vfs-read-wait 0 --buffer-size off --vfs-read-chunk-size-limit 32k --no-check-dest --no-checksum --no-modtime --no-traverse --read-only --daemon
sleep 2
rclone mount ac:/79/ /mnt/79/ --drive-service-account-file /root/79.json --vfs-read-chunk-size 64k --vfs-cache-max-size 1G --transfers 128 --checkers 256 --drive-pacer-min-sleep 1ms --drive-pacer-burst 200 --poll-interval 224h --vfs-cache-mode full --dir-cache-time 1000000h --vfs-cache-max-age 1000000h --vfs-cache-poll-interval 33332m --max-read-ahead 128k --vfs-read-ahead 32k --vfs-read-wait 0 --buffer-size off --vfs-read-chunk-size-limit 32k --no-check-dest --no-checksum --no-modtime --no-traverse --read-only --daemon
sleep 2
rclone mount ac:/80/ /mnt/80/ --drive-service-account-file /root/80.json --vfs-read-chunk-size 64k --vfs-cache-max-size 1G --transfers 128 --checkers 256 --drive-pacer-min-sleep 1ms --drive-pacer-burst 200 --poll-interval 224h --vfs-cache-mode full --dir-cache-time 1000000h --vfs-cache-max-age 1000000h --vfs-cache-poll-interval 33332m --max-read-ahead 128k --vfs-read-ahead 32k --vfs-read-wait 0 --buffer-size off --vfs-read-chunk-size-limit 32k --no-check-dest --no-checksum --no-modtime --no-traverse --read-only --daemon
sleep 2
cd /mnt
du -h