rclone mount ac:/41/ /mnt/41/ --drive-service-account-file /root/41.json --vfs-read-chunk-size 64k --vfs-cache-max-size 1G --transfers 128 --checkers 256 --drive-pacer-min-sleep 1ms --drive-pacer-burst 200 --poll-interval 224h --vfs-cache-mode full --dir-cache-time 1000000h --vfs-cache-max-age 1000000h --vfs-cache-poll-interval 33332m --max-read-ahead 128k --vfs-read-ahead 32k --vfs-read-wait 0 --buffer-size off --vfs-read-chunk-size-limit 32k --no-check-dest --no-checksum --no-modtime --no-traverse --read-only --daemon
sleep 2
rclone mount ac:/42/ /mnt/42/ --drive-service-account-file /root/42.json --vfs-read-chunk-size 64k --vfs-cache-max-size 1G --transfers 128 --checkers 256 --drive-pacer-min-sleep 1ms --drive-pacer-burst 200 --poll-interval 224h --vfs-cache-mode full --dir-cache-time 1000000h --vfs-cache-max-age 1000000h --vfs-cache-poll-interval 33332m --max-read-ahead 128k --vfs-read-ahead 32k --vfs-read-wait 0 --buffer-size off --vfs-read-chunk-size-limit 32k --no-check-dest --no-checksum --no-modtime --no-traverse --read-only --daemon
sleep 2
rclone mount ac:/43/ /mnt/43/ --drive-service-account-file /root/43.json --vfs-read-chunk-size 64k --vfs-cache-max-size 1G --transfers 128 --checkers 256 --drive-pacer-min-sleep 1ms --drive-pacer-burst 200 --poll-interval 224h --vfs-cache-mode full --dir-cache-time 1000000h --vfs-cache-max-age 1000000h --vfs-cache-poll-interval 33332m --max-read-ahead 128k --vfs-read-ahead 32k --vfs-read-wait 0 --buffer-size off --vfs-read-chunk-size-limit 32k --no-check-dest --no-checksum --no-modtime --no-traverse --read-only --daemon
sleep 2
rclone mount ac:/44/ /mnt/44/ --drive-service-account-file /root/44.json --vfs-read-chunk-size 64k --vfs-cache-max-size 1G --transfers 128 --checkers 256 --drive-pacer-min-sleep 1ms --drive-pacer-burst 200 --poll-interval 224h --vfs-cache-mode full --dir-cache-time 1000000h --vfs-cache-max-age 1000000h --vfs-cache-poll-interval 33332m --max-read-ahead 128k --vfs-read-ahead 32k --vfs-read-wait 0 --buffer-size off --vfs-read-chunk-size-limit 32k --no-check-dest --no-checksum --no-modtime --no-traverse --read-only --daemon
sleep 2
rclone mount ac:/45/ /mnt/45/ --drive-service-account-file /root/45.json --vfs-read-chunk-size 64k --vfs-cache-max-size 1G --transfers 128 --checkers 256 --drive-pacer-min-sleep 1ms --drive-pacer-burst 200 --poll-interval 224h --vfs-cache-mode full --dir-cache-time 1000000h --vfs-cache-max-age 1000000h --vfs-cache-poll-interval 33332m --max-read-ahead 128k --vfs-read-ahead 32k --vfs-read-wait 0 --buffer-size off --vfs-read-chunk-size-limit 32k --no-check-dest --no-checksum --no-modtime --no-traverse --read-only --daemon
sleep 2
cd /mnt
du -h